name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Android SDK
      run: |
        mkdir -p ~/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip commandlinetools-linux-* -d ~/android-sdk/cmdline-tools
        mv ~/android-sdk/cmdline-tools/cmdline-tools ~/android-sdk/cmdline-tools/latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

    - name: Accept Licenses
      run: |
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android Platform
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0"

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create Qaalim com.qaalim.app Qaalim
        mkdir -p Qaalim/www
        cp -r www/* Qaalim/www/ || true
        cp config.xml Qaalim/

    - name: Add Android Platform
      working-directory: ./Qaalim
      run: cordova platform add android@14.0.0

    - name: Build APK
      working-directory: ./Qaalim
      run: cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: qaalim-app
        path: Qaalim/platforms/android/app/build/outputs/apk/**/*.apk
