name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create Qaalim com.qaalim.app Qaalim
        cp -r www/* Qaalim/www/
        cp config.xml Qaalim/

    - name: Add Android Platform
      working-directory: ./Qaalim
      run: |
        cordova platform add android@9.0.0

    - name: Build APK
      working-directory: ./Qaalim
      run: cordova build android

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: qaalim-app
        path: Qaalim/platforms/android/app/build/outputs/apk/debug/app-debug.apk
