name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Updated to current LTS

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create Qaalim com.qaalim.app Qaalim
        cp -r www/* Qaalim/www/
        cp config.xml Qaalim/

    - name: Add Android Platform
      working-directory: ./Qaalim
      run: |
        cordova platform add android@14.0.0  # Latest Android platform
        yes | sdkmanager --licenses  # Accept Android licenses

    - name: Build APK
      working-directory: ./Qaalim
      run: |
        cordova build android -- --packageType=apk

    - name: Upload APK
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: qaalim-app
        path: Qaalim/platforms/android/app/build/outputs/apk/**/*.apk
